# Array Input and Output

# Create an array

In [2]:
import numpy as np

In [3]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
#Save Array 
np.save('my_array',arr)

In [7]:
#Load Array 
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
#testing

from numpy.random import randn
arr=randn(3,3)
arr

array([[ 0.25142664, -0.22953323,  0.6473465 ],
       [ 0.88507469,  0.48949682,  0.07581244],
       [-0.9372316 , -0.56285043,  0.30374944]])

In [9]:
arr[1],arr[2]

(array([ 0.88507469,  0.48949682,  0.07581244]),
 array([-0.9372316 , -0.56285043,  0.30374944]))

In [10]:
arr[1][1],arr[1][2],arr[2][1],arr[2][2]

(0.48949682160867447,
 0.075812444612983393,
 -0.56285042922843753,
 0.3037494441676612)

In [16]:
arr[:,1]

array([-0.22953323,  0.48949682, -0.56285043])