# Scalars

In [1]:
import numpy as np 

In [2]:
print(5+2)

7


In [3]:
print(5-2)

3


In [4]:
print(5*2)

10


In [5]:
print(5/2)

2.5


In [6]:
print(5%2)

1


In [7]:
print(5**2)

25


In [10]:
arr1=np.array([[1,2,3],[8,9,10]])
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [11]:
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [12]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [15]:
arr1**3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)

In [17]:
#Task
#1-Creat a array with ones (3,3)
#2-then add two unit to each of the item
#3-and also return its square 

In [20]:
arr1=np.ones((3,3))

In [24]:
arr2=arr1+2

In [25]:
arr2**2

array([[ 9.,  9.,  9.],
       [ 9.,  9.,  9.],
       [ 9.,  9.,  9.]])

In [31]:
arr1=np.ones((3,3))
print(arr1)
print('--------------')
arr2=arr1+2
print(arr2)
print('--------------')
finalarray=arr2**2
print(finalarray)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
--------------
[[ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]]
--------------
[[ 9.  9.  9.]
 [ 9.  9.  9.]
 [ 9.  9.  9.]]
