# Array

In [1]:
import numpy as np 

my_list1=[1,2,3,4]
my_array=np.array(my_list1)
my_list1

[1, 2, 3, 4]

In [2]:
my_list2=[11,22,33,44]
my_lists=[my_array,my_list2]
my_array2=np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [3]:
my_array2.shape

(2, 4)

In [4]:
my_array2.dtype

dtype('int32')

In [6]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [9]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [10]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
#first task 
#please write this code 
#array[20,18,16,14,12,10,8,6]

In [16]:
np.arange(20,5,-2)

array([20, 18, 16, 14, 12, 10,  8,  6])