# Indexing Arrays 

In [7]:
import numpy as np 
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[8]

8

In [6]:
#create an array starts with 0 
#end is 20, interval is 3
#please show the value of index 3

In [13]:
arr=np.arange(0,20,3)
print(arr)
arr[3]

[ 0  3  6  9 12 15 18]


9

In [16]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[1:5]

array([1, 2, 3, 4])

In [18]:
arr[0:5] #start from zero, with 5 length 

array([0, 1, 2, 3, 4])

In [20]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
slice_of_arr[:]=99 #all row all column
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d=np.array(([5,10,50],[20,25,30],[35,40,45]))   #2 dimensional arrays
arr_2d

array([[ 5, 10, 50],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[2] #it shows the third row

array([35, 40, 45])

In [24]:
arr_2d[0] #it shows the first row

array([ 5, 10, 50])

In [11]:
arr_2d[1][0] #it shows second row and first column

20

In [12]:
arr_2d[0] 

array([ 5, 10, 50])

In [25]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[:,2]

array([50, 30, 45])