# Numpy.where and Random

In [2]:
import numpy as np

In [5]:
from numpy.random import randn

arr=randn(5,5)
arr

array([[ 0.69786284,  0.00294551, -0.73113073, -0.72409238, -0.56756871],
       [ 1.15062013, -0.69965135, -0.52629294,  0.59303647,  0.48112102],
       [ 0.28268825, -0.80435907,  0.11165784, -0.88570793, -0.32612832],
       [-0.51909775, -1.2164354 , -1.3242673 ,  0.02736945, -0.4624065 ],
       [-0.71063813,  0.27964952, -1.457469  ,  1.18480227, -0.67526891]])

In [6]:
np.where(arr<0,0,arr)

array([[ 0.69786284,  0.00294551,  0.        ,  0.        ,  0.        ],
       [ 1.15062013,  0.        ,  0.        ,  0.59303647,  0.48112102],
       [ 0.28268825,  0.        ,  0.11165784,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.02736945,  0.        ],
       [ 0.        ,  0.27964952,  0.        ,  1.18480227,  0.        ]])

In [9]:
np.where(arr<0,100,arr)

array([[  6.97862842e-01,   2.94550560e-03,   1.00000000e+02,
          1.00000000e+02,   1.00000000e+02],
       [  1.15062013e+00,   1.00000000e+02,   1.00000000e+02,
          5.93036470e-01,   4.81121020e-01],
       [  2.82688252e-01,   1.00000000e+02,   1.11657840e-01,
          1.00000000e+02,   1.00000000e+02],
       [  1.00000000e+02,   1.00000000e+02,   1.00000000e+02,
          2.73694454e-02,   1.00000000e+02],
       [  1.00000000e+02,   2.79649516e-01,   1.00000000e+02,
          1.18480227e+00,   1.00000000e+02]])

# Create Array and Sum,Mean, Variance, Standard Deviation

In [12]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.sum()

45

In [14]:
arr.sum(0)

array([12, 15, 18])

In [15]:
arr.sum(1)

array([ 6, 15, 24])

In [16]:
arr.mean()

5.0

In [17]:
arr.std()

2.5819888974716112

In [18]:
arr.var()

6.666666666666667

# Boolean Array

In [20]:
bool_arr=np.array([True,False,False])
bool_arr

array([ True, False, False], dtype=bool)

In [21]:
bool_arr.any()

True

In [22]:
bool_arr.all()

False

# Sort Array

In [25]:
arr=randn(5)
arr

array([-1.50226028, -0.59373266, -0.94511847,  1.53538536,  1.21970792])

In [26]:
arr.sort()
arr

array([-1.50226028, -0.94511847, -0.59373266,  1.21970792,  1.53538536])

# Unique and in 1d

In [27]:
countries=(['France','Germany','USA','Russia','Mexico','Germany','USA'])
countries

['France', 'Germany', 'USA', 'Russia', 'Mexico', 'Germany', 'USA']

In [28]:
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], 
      dtype='<U7')

In [30]:
np.in1d(['France','Germany','Sweden'],countries)
#To check if the variable is inside the countries or not 

array([ True,  True, False], dtype=bool)