# UNIVERSAL ARRAY FUNCTION

# Create Sample 1d array

In [2]:
import numpy as np

In [5]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

# Create First Array

In [9]:
A=np.arange(5)
A

array([0, 1, 2, 3, 4])

In [10]:
B=np.arange(-1,4)
B

array([-1,  0,  1,  2,  3])

# Addition Both Array

In [13]:
np.add(A,B)

array([-1,  1,  3,  5,  7])

# Max and Min both array

In [15]:
np.max(A)

4

In [16]:
np.min(B)

-1

In [18]:
np.maximum(A,B)

array([0, 1, 2, 3, 4])

In [19]:
#Create sample array with start value 1, end value 20, interval 2
#taking square root 
#create another array with data as even value 0 to 20 
#find min and max 

In [21]:
arr_task=np.arange(1,20,2)
arr_task

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
np.sqrt(arr_task)

array([ 1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ,
        3.31662479,  3.60555128,  3.87298335,  4.12310563,  4.35889894])

In [23]:
arr_task2=np.arange(0,20,2)
arr_task2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.add(arr_task,arr_task2)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [26]:
np.minimum(arr_task,arr_task2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.maximum(arr_task,arr_task2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])