In [1]:
import numpy as np 

In [32]:
arr_2d=np.array(([5,10,50],[20,25,30],[35,40,45]))   #2 dimensional arrays
arr_2d

array([[ 5, 10, 50],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[0:2,1:] #replace first two rows and last two columns with 100

array([[10, 50],
       [25, 30]])

In [38]:
arr_2d[1:] #show last two rows 

array([[20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])